name: flutter_ionicons_app
description: This application includes all icons provided by the flutter-ionicons package.

publish_to: 'none'

version: 0.2.1+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ionicons: ^0.2.1
  flutter_riverpod: ^1.0.4
  url_launcher: ^6.1.5
  flutter_displaymode: ^0.4.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  hive_generator: ^1.1.3
  build_runner: ^2.2.0

flutter:

  uses-material-design: true
